---
- name: Install nginx
  apt: pkg=nginx state=latest

- name: Create nginx main configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create wordpress nginx configuration
  template: src=wordpress.conf dest=/etc/nginx/sites-available/wordpress.conf

- name: Delete default nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Create link for nginx configuration
  file: src=/etc/nginx/sites-available/wordpress.conf dest=/etc/nginx/sites-enabled/wordpress.conf state=link
  notify: restart nginx
